In [1]:
import sqlite3
import pandas as pd

In [2]:
df = pd.read_csv("dataanalytics.csv")

In [3]:
print("="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

print(df.head())

============================================================
DATASET LOADED SUCCESSFULLY
============================================================
     OrderID        Date CustomerID  Product  Quantity  UnitPrice  \
0  ORD200000  2023-01-04     C72649  Monitor         5     570.62
1  ORD200001  2024-08-23     C75739    Phone         2     151.35
2  ORD200002  2024-02-27     C81728   Tablet         5     550.68
3  ORD200003  2023-10-15     C33540    Chair         1     273.19
4  ORD200004  2025-05-08     C81840  Printer         4     626.01

  ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0     928 Main St    Debit Card     Shipped    TRK37947903            7
1     823 Main St        Online     Shipped    TRK91186779            3
2     512 Main St   Credit Card   Cancelled    TRK42903982            8
3     275 Main St    Debit Card    Returned    TRK62788070            5
4     668 Main St        Online   Delivered    TRK29241424            8

  CouponCode ReferralSource  TotalPrice
0     SAVE10      Instagram     2853.10
1     SAVE10       Referral      302.70
2   FREESHIP          Email     2753.40
3     SAVE10       Facebook      273.19
4     SAVE10          Email     2504.04

In [4]:
conn = sqlite3.connect(":memory:")

df.to_sql(
    "orders",
    conn,
    index=False,
    if_exists="replace"
)

print("\nDatabase Created Successfully!")

Database Created Successfully!

In [5]:
def run_query(title, query):

    print("\n")
    print("="*80)
    print(title)
    print("="*80)

    print(query)

    result = pd.read_sql_query(query, conn)

    print("-"*80)
    print(result)

    return result

In [8]:
run_query(
"1. View First 10 Records",

"""
SELECT *
FROM orders
LIMIT 10;

"""
)

================================================================================
1. View First 10 Records
================================================================================

SELECT *
FROM orders
LIMIT 10;


--------------------------------------------------------------------------------
     OrderID        Date CustomerID  Product  Quantity  UnitPrice  \
0  ORD200000  2023-01-04     C72649  Monitor         5     570.62
1  ORD200001  2024-08-23     C75739    Phone         2     151.35
2  ORD200002  2024-02-27     C81728   Tablet         5     550.68
3  ORD200003  2023-10-15     C33540    Chair         1     273.19
4  ORD200004  2025-05-08     C81840  Printer         4     626.01
5  ORD200005  2023-10-23     C37249    Phone         2     245.86
6  ORD200006  2025-06-17     C83492   Laptop         1     664.42
7  ORD200007  2023-05-12     C41460  Monitor         5     149.55
8  ORD200008  2025-04-02     C26817    Phone         2     134.28
9  ORD200009  2023-11-21     C31946     Desk         4     509.38

  ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0     928 Main St    Debit Card     Shipped    TRK37947903            7
1     823 Main St        Online     Shipped    TRK91186779            3
2     512 Main St   Credit Card   Cancelled    TRK42903982            8
3     275 Main St    Debit Card    Returned    TRK62788070            5
4     668 Main St        Online   Delivered    TRK29241424            8
5     934 Main St   Credit Card     Shipped    TRK72976927            4
6     986 Main St     Gift Card    Returned    TRK96417362            6
7     706 Main St          Cash     Shipped    TRK78809193            9
8     904 Main St     Gift Card   Cancelled    TRK61042692            2
9     102 Main St   Credit Card     Shipped    TRK33478363            6

  CouponCode ReferralSource  TotalPrice
0     SAVE10      Instagram     2853.10
1     SAVE10       Referral      302.70
2   FREESHIP          Email     2753.40
3     SAVE10       Facebook      273.19
4     SAVE10          Email     2504.04
5     SAVE10      Instagram      491.72
6     SAVE10       Facebook      664.42
7   FREESHIP       Facebook      747.75
8       None          Email      268.56
9     SAVE10         Google     2037.52

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,None,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [9]:
run_query(
"2. Display Only Important Columns",

"""
SELECT
OrderID,
Product,
Quantity,
UnitPrice,
TotalPrice
FROM orders
LIMIT 10;

"""
)

================================================================================
2. Display Only Important Columns
================================================================================

SELECT
OrderID,
Product,
Quantity,
UnitPrice,
TotalPrice
FROM orders
LIMIT 10;


--------------------------------------------------------------------------------
     OrderID  Product  Quantity  UnitPrice  TotalPrice
0  ORD200000  Monitor         5     570.62     2853.10
1  ORD200001    Phone         2     151.35      302.70
2  ORD200002   Tablet         5     550.68     2753.40
3  ORD200003    Chair         1     273.19      273.19
4  ORD200004  Printer         4     626.01     2504.04
5  ORD200005    Phone         2     245.86      491.72
6  ORD200006   Laptop         1     664.42      664.42
7  ORD200007  Monitor         5     149.55      747.75
8  ORD200008    Phone         2     134.28      268.56
9  ORD200009     Desk         4     509.38     2037.52

     OrderID  Product  Quantity  UnitPrice  TotalPrice
0  ORD200000  Monitor         5     570.62     2853.10
1  ORD200001    Phone         2     151.35      302.70
2  ORD200002   Tablet         5     550.68     2753.40
3  ORD200003    Chair         1     273.19      273.19
4  ORD200004  Printer         4     626.01     2504.04
5  ORD200005    Phone         2     245.86      491.72
6  ORD200006   Laptop         1     664.42      664.42
7  ORD200007  Monitor         5     149.55      747.75
8  ORD200008    Phone         2     134.28      268.56
9  ORD200009     Desk         4     509.38     2037.52

In [10]:
run_query(
"3. Display Unique Products",

"""
SELECT DISTINCT Product
FROM orders;

"""
)

================================================================================
3. Display Unique Products
================================================================================

SELECT DISTINCT Product
FROM orders;


--------------------------------------------------------------------------------
   Product
0  Monitor
1    Phone
2   Tablet
3    Chair
4  Printer
5   Laptop
6     Desk

   Product
0  Monitor
1    Phone
2   Tablet
3    Chair
4  Printer
5   Laptop
6     Desk

In [11]:
run_query(
"4. Display Unique Payment Methods",

"""
SELECT DISTINCT PaymentMethod
FROM orders;

"""
)

================================================================================
4. Display Unique Payment Methods
================================================================================

SELECT DISTINCT PaymentMethod
FROM orders;


--------------------------------------------------------------------------------
  PaymentMethod
0    Debit Card
1        Online
2   Credit Card
3     Gift Card
4          Cash

  PaymentMethod
0    Debit Card
1        Online
2   Credit Card
3     Gift Card
4          Cash

In [12]:
run_query(
"5. Display Unique Order Status",

"""
SELECT DISTINCT OrderStatus
FROM orders;

"""
)

================================================================================
5. Display Unique Order Status
================================================================================

SELECT DISTINCT OrderStatus
FROM orders;


--------------------------------------------------------------------------------
  OrderStatus
0     Shipped
1   Cancelled
2    Returned
3   Delivered
4     Pending

  OrderStatus
0     Shipped
1   Cancelled
2    Returned
3   Delivered
4     Pending

In [13]:
run_query(
"6. Orders Having TotalPrice Greater Than 2000",

"""

SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE TotalPrice > 2000;

"""
)

================================================================================
6. Orders Having TotalPrice Greater Than 2000
================================================================================


SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE TotalPrice > 2000;


--------------------------------------------------------------------------------
       OrderID  Product  TotalPrice
0    ORD200000  Monitor     2853.10
1    ORD200002   Tablet     2753.40
2    ORD200004  Printer     2504.04
3    ORD200009     Desk     2037.52
4    ORD200010   Tablet     3129.85
..         ...      ...         ...
175  ORD201155  Printer     2138.28
176  ORD201156   Laptop     2763.12
177  ORD201171    Phone     2073.60
178  ORD201179   Laptop     2592.75
179  ORD201199   Tablet     2242.32

[180 rows x 3 columns]

       OrderID  Product  TotalPrice
0    ORD200000  Monitor     2853.10
1    ORD200002   Tablet     2753.40
2    ORD200004  Printer     2504.04
3    ORD200009     Desk     2037.52
4    ORD200010   Tablet     3129.85
..         ...      ...         ...
175  ORD201155  Printer     2138.28
176  ORD201156   Laptop     2763.12
177  ORD201171    Phone     2073.60
178  ORD201179   Laptop     2592.75
179  ORD201199   Tablet     2242.32

[180 rows x 3 columns]

In [14]:
run_query(
"7. Delivered Orders",

"""

SELECT
OrderID,
Product,
OrderStatus

FROM orders

WHERE OrderStatus='Delivered';

"""
)

================================================================================
7. Delivered Orders
================================================================================


SELECT
OrderID,
Product,
OrderStatus

FROM orders

WHERE OrderStatus='Delivered';


--------------------------------------------------------------------------------
       OrderID  Product OrderStatus
0    ORD200004  Printer   Delivered
1    ORD200015  Printer   Delivered
2    ORD200021  Monitor   Delivered
3    ORD200024   Laptop   Delivered
4    ORD200025  Monitor   Delivered
..         ...      ...         ...
226  ORD201166    Chair   Delivered
227  ORD201168   Laptop   Delivered
228  ORD201171    Phone   Delivered
229  ORD201187     Desk   Delivered
230  ORD201197   Tablet   Delivered

[231 rows x 3 columns]

       OrderID  Product OrderStatus
0    ORD200004  Printer   Delivered
1    ORD200015  Printer   Delivered
2    ORD200021  Monitor   Delivered
3    ORD200024   Laptop   Delivered
4    ORD200025  Monitor   Delivered
..         ...      ...         ...
226  ORD201166    Chair   Delivered
227  ORD201168   Laptop   Delivered
228  ORD201171    Phone   Delivered
229  ORD201187     Desk   Delivered
230  ORD201197   Tablet   Delivered

[231 rows x 3 columns]

In [15]:
run_query(
"8. Cancelled Orders",

"""

SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE OrderStatus='Cancelled';

"""
)

================================================================================
8. Cancelled Orders
================================================================================


SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE OrderStatus='Cancelled';


--------------------------------------------------------------------------------
       OrderID  Product  TotalPrice
0    ORD200002   Tablet     2753.40
1    ORD200008    Phone      268.56
2    ORD200023    Phone     1093.00
3    ORD200033    Chair      162.77
4    ORD200042  Printer      303.32
..         ...      ...         ...
245  ORD201179   Laptop     2592.75
246  ORD201189   Tablet     1946.10
247  ORD201195     Desk      107.04
248  ORD201196  Monitor     1325.06
249  ORD201198    Chair     1050.08

[250 rows x 3 columns]

       OrderID  Product  TotalPrice
0    ORD200002   Tablet     2753.40
1    ORD200008    Phone      268.56
2    ORD200023    Phone     1093.00
3    ORD200033    Chair      162.77
4    ORD200042  Printer      303.32
..         ...      ...         ...
245  ORD201179   Laptop     2592.75
246  ORD201189   Tablet     1946.10
247  ORD201195     Desk      107.04
248  ORD201196  Monitor     1325.06
249  ORD201198    Chair     1050.08

[250 rows x 3 columns]

In [16]:
run_query(
"9. Credit Card Payments",

"""

SELECT
OrderID,
PaymentMethod,
TotalPrice

FROM orders

WHERE PaymentMethod='Credit Card';

"""
)

================================================================================
9. Credit Card Payments
================================================================================


SELECT
OrderID,
PaymentMethod,
TotalPrice

FROM orders

WHERE PaymentMethod='Credit Card';


--------------------------------------------------------------------------------
       OrderID PaymentMethod  TotalPrice
0    ORD200002   Credit Card     2753.40
1    ORD200005   Credit Card      491.72
2    ORD200009   Credit Card     2037.52
3    ORD200010   Credit Card     3129.85
4    ORD200013   Credit Card      604.47
..         ...           ...         ...
229  ORD201174   Credit Card      667.02
230  ORD201178   Credit Card       70.24
231  ORD201179   Credit Card     2592.75
232  ORD201190   Credit Card     1849.17
233  ORD201195   Credit Card      107.04

[234 rows x 3 columns]

       OrderID PaymentMethod  TotalPrice
0    ORD200002   Credit Card     2753.40
1    ORD200005   Credit Card      491.72
2    ORD200009   Credit Card     2037.52
3    ORD200010   Credit Card     3129.85
4    ORD200013   Credit Card      604.47
..         ...           ...         ...
229  ORD201174   Credit Card      667.02
230  ORD201178   Credit Card       70.24
231  ORD201179   Credit Card     2592.75
232  ORD201190   Credit Card     1849.17
233  ORD201195   Credit Card      107.04

[234 rows x 3 columns]

In [17]:
run_query(
"10. Orders Between ₹1000 and ₹2000",

"""

SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE TotalPrice
BETWEEN 1000
AND 2000;

"""
)

================================================================================
10. Orders Between ₹1000 and ₹2000
================================================================================


SELECT
OrderID,
Product,
TotalPrice

FROM orders

WHERE TotalPrice
BETWEEN 1000
AND 2000;


--------------------------------------------------------------------------------
       OrderID  Product  TotalPrice
0    ORD200016  Printer     1067.62
1    ORD200019  Monitor     1120.00
2    ORD200021  Monitor     1371.80
3    ORD200023    Phone     1093.00
4    ORD200029     Desk     1270.59
..         ...      ...         ...
327  ORD201190     Desk     1849.17
328  ORD201191     Desk     1505.72
329  ORD201192    Chair     1298.55
330  ORD201196  Monitor     1325.06
331  ORD201198    Chair     1050.08

[332 rows x 3 columns]

       OrderID  Product  TotalPrice
0    ORD200016  Printer     1067.62
1    ORD200019  Monitor     1120.00
2    ORD200021  Monitor     1371.80
3    ORD200023    Phone     1093.00
4    ORD200029     Desk     1270.59
..         ...      ...         ...
327  ORD201190     Desk     1849.17
328  ORD201191     Desk     1505.72
329  ORD201192    Chair     1298.55
330  ORD201196  Monitor     1325.06
331  ORD201198    Chair     1050.08

[332 rows x 3 columns]

In [18]:
run_query(
"11. Addresses Containing Main St",

"""

SELECT
OrderID,
ShippingAddress

FROM orders

WHERE ShippingAddress
LIKE '%Main St%'

LIMIT 10;

"""
)

================================================================================
11. Addresses Containing Main St
================================================================================


SELECT
OrderID,
ShippingAddress

FROM orders

WHERE ShippingAddress
LIKE '%Main St%'

LIMIT 10;


--------------------------------------------------------------------------------
     OrderID ShippingAddress
0  ORD200000     928 Main St
1  ORD200001     823 Main St
2  ORD200002     512 Main St
3  ORD200003     275 Main St
4  ORD200004     668 Main St
5  ORD200005     934 Main St
6  ORD200006     986 Main St
7  ORD200007     706 Main St
8  ORD200008     904 Main St
9  ORD200009     102 Main St

     OrderID ShippingAddress
0  ORD200000     928 Main St
1  ORD200001     823 Main St
2  ORD200002     512 Main St
3  ORD200003     275 Main St
4  ORD200004     668 Main St
5  ORD200005     934 Main St
6  ORD200006     986 Main St
7  ORD200007     706 Main St
8  ORD200008     904 Main St
9  ORD200009     102 Main St

In [19]:
run_query(
"12. Orders Paid Using Cash or Debit Card",

"""

SELECT
OrderID,
PaymentMethod,
TotalPrice

FROM orders

WHERE PaymentMethod
IN
(
'Cash',
'Debit Card'
);

"""
)

================================================================================
12. Orders Paid Using Cash or Debit Card
================================================================================


SELECT
OrderID,
PaymentMethod,
TotalPrice

FROM orders

WHERE PaymentMethod
IN
(
'Cash',
'Debit Card'
);


--------------------------------------------------------------------------------
       OrderID PaymentMethod  TotalPrice
0    ORD200000    Debit Card     2853.10
1    ORD200003    Debit Card      273.19
2    ORD200007          Cash      747.75
3    ORD200012    Debit Card      361.00
4    ORD200014    Debit Card      786.66
..         ...           ...         ...
473  ORD201186          Cash      163.32
474  ORD201189          Cash     1946.10
475  ORD201193          Cash      687.89
476  ORD201194          Cash      568.32
477  ORD201198    Debit Card     1050.08

[478 rows x 3 columns]

       OrderID PaymentMethod  TotalPrice
0    ORD200000    Debit Card     2853.10
1    ORD200003    Debit Card      273.19
2    ORD200007          Cash      747.75
3    ORD200012    Debit Card      361.00
4    ORD200014    Debit Card      786.66
..         ...           ...         ...
473  ORD201186          Cash      163.32
474  ORD201189          Cash     1946.10
475  ORD201193          Cash      687.89
476  ORD201194          Cash      568.32
477  ORD201198    Debit Card     1050.08

[478 rows x 3 columns]

In [20]:
run_query(
"13. Top 10 Highest Value Orders",

"""

SELECT
OrderID,
Product,
TotalPrice

FROM orders

ORDER BY
TotalPrice DESC

LIMIT 10;

"""
)

================================================================================
13. Top 10 Highest Value Orders
================================================================================


SELECT
OrderID,
Product,
TotalPrice

FROM orders

ORDER BY
TotalPrice DESC

LIMIT 10;


--------------------------------------------------------------------------------
     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

In [21]:
run_query(
"14. Lowest Value Orders",

"""

SELECT
OrderID,
Product,
TotalPrice

FROM orders

ORDER BY
TotalPrice ASC

LIMIT 10;

"""
)

================================================================================
14. Lowest Value Orders
================================================================================


SELECT
OrderID,
Product,
TotalPrice

FROM orders

ORDER BY
TotalPrice ASC

LIMIT 10;


--------------------------------------------------------------------------------
     OrderID  Product  TotalPrice
0  ORD201161    Phone       11.39
1  ORD200863    Phone       14.06
2  ORD200240   Tablet       17.24
3  ORD200542   Tablet       17.98
4  ORD200336   Laptop       18.20
5  ORD200776   Tablet       21.19
6  ORD201025    Chair       23.53
7  ORD200690  Monitor       24.48
8  ORD200926     Desk       26.95
9  ORD200473    Chair       29.86

     OrderID  Product  TotalPrice
0  ORD201161    Phone       11.39
1  ORD200863    Phone       14.06
2  ORD200240   Tablet       17.24
3  ORD200542   Tablet       17.98
4  ORD200336   Laptop       18.20
5  ORD200776   Tablet       21.19
6  ORD201025    Chair       23.53
7  ORD200690  Monitor       24.48
8  ORD200926     Desk       26.95
9  ORD200473    Chair       29.86

In [22]:
run_query(
"15. Products in Alphabetical Order",

"""

SELECT DISTINCT Product

FROM orders

ORDER BY Product ASC;

"""
)

================================================================================
15. Products in Alphabetical Order
================================================================================


SELECT DISTINCT Product

FROM orders

ORDER BY Product ASC;


--------------------------------------------------------------------------------
   Product
0    Chair
1     Desk
2   Laptop
3  Monitor
4    Phone
5  Printer
6   Tablet

   Product
0    Chair
1     Desk
2   Laptop
3  Monitor
4    Phone
5  Printer
6   Tablet

In [23]:
run_query(
"16. Total Number of Orders",

"""
SELECT
COUNT(*) AS TotalOrders
FROM orders;

"""
)

================================================================================
16. Total Number of Orders
================================================================================

SELECT
COUNT(*) AS TotalOrders
FROM orders;


--------------------------------------------------------------------------------
   TotalOrders
0         1200

   TotalOrders
0         1200

In [24]:
run_query(
"17. Total Revenue Generated",

"""
SELECT
ROUND(SUM(TotalPrice),2) AS TotalRevenue
FROM orders;

"""
)

================================================================================
17. Total Revenue Generated
================================================================================

SELECT
ROUND(SUM(TotalPrice),2) AS TotalRevenue
FROM orders;


--------------------------------------------------------------------------------
   TotalRevenue
0    1264761.96

   TotalRevenue
0    1264761.96

In [25]:
run_query(
"18. Average Order Value",

"""
SELECT
ROUND(AVG(TotalPrice),2) AS AverageOrderValue
FROM orders;

"""
)

================================================================================
18. Average Order Value
================================================================================

SELECT
ROUND(AVG(TotalPrice),2) AS AverageOrderValue
FROM orders;


--------------------------------------------------------------------------------
   AverageOrderValue
0            1053.97

   AverageOrderValue
0            1053.97

In [26]:
run_query(
"19. Highest Order Value",

"""
SELECT
MAX(TotalPrice) AS HighestOrder
FROM orders;

"""
)

================================================================================
19. Highest Order Value
================================================================================

SELECT
MAX(TotalPrice) AS HighestOrder
FROM orders;


--------------------------------------------------------------------------------
   HighestOrder
0        3456.4

   HighestOrder
0        3456.4

In [27]:
run_query(
"20. Lowest Order Value",

"""
SELECT
MIN(TotalPrice) AS LowestOrder
FROM orders;

"""
)

================================================================================
20. Lowest Order Value
================================================================================

SELECT
MIN(TotalPrice) AS LowestOrder
FROM orders;


--------------------------------------------------------------------------------
   LowestOrder
0        11.39

   LowestOrder
0        11.39

In [28]:
run_query(
"21. Average Unit Price",

"""
SELECT
ROUND(AVG(UnitPrice),2) AS AverageUnitPrice
FROM orders;

"""
)

================================================================================
21. Average Unit Price
================================================================================

SELECT
ROUND(AVG(UnitPrice),2) AS AverageUnitPrice
FROM orders;


--------------------------------------------------------------------------------
   AverageUnitPrice
0            356.41

   AverageUnitPrice
0            356.41

In [29]:
run_query(
"22. Number of Orders Per Product",

"""
SELECT
Product,
COUNT(*) AS TotalOrders

FROM orders

GROUP BY Product

ORDER BY TotalOrders DESC;

"""
)

================================================================================
22. Number of Orders Per Product
================================================================================

SELECT
Product,
COUNT(*) AS TotalOrders

FROM orders

GROUP BY Product

ORDER BY TotalOrders DESC;


--------------------------------------------------------------------------------
   Product  TotalOrders
0  Printer          181
1   Tablet          179
2    Chair          178
3   Laptop          173
4     Desk          170
5  Monitor          163
6    Phone          156

   Product  TotalOrders
0  Printer          181
1   Tablet          179
2    Chair          178
3   Laptop          173
4     Desk          170
5  Monitor          163
6    Phone          156

In [30]:
run_query(
"23. Revenue Generated By Each Product",

"""
SELECT
Product,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

ORDER BY Revenue DESC;

"""
)

================================================================================
23. Revenue Generated By Each Product
================================================================================

SELECT
Product,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

In [31]:
run_query(
"24. Average Revenue Per Product",

"""
SELECT
Product,
ROUND(AVG(TotalPrice),2) AS AvgRevenue

FROM orders

GROUP BY Product

ORDER BY AvgRevenue DESC;

"""
)

================================================================================
24. Average Revenue Per Product
================================================================================

SELECT
Product,
ROUND(AVG(TotalPrice),2) AS AvgRevenue

FROM orders

GROUP BY Product

ORDER BY AvgRevenue DESC;


--------------------------------------------------------------------------------
   Product  AvgRevenue
0   Laptop     1110.56
1    Chair     1098.99
2  Printer     1080.73
3  Monitor     1077.62
4   Tablet     1042.28
5     Desk      985.06
6    Phone      972.58

   Product  AvgRevenue
0   Laptop     1110.56
1    Chair     1098.99
2  Printer     1080.73
3  Monitor     1077.62
4   Tablet     1042.28
5     Desk      985.06
6    Phone      972.58

In [32]:
run_query(
"25. Total Quantity Sold Per Product",

"""
SELECT
Product,
SUM(Quantity) AS TotalQuantity

FROM orders

GROUP BY Product

ORDER BY TotalQuantity DESC;

"""
)

================================================================================
25. Total Quantity Sold Per Product
================================================================================

SELECT
Product,
SUM(Quantity) AS TotalQuantity

FROM orders

GROUP BY Product

ORDER BY TotalQuantity DESC;


--------------------------------------------------------------------------------
   Product  TotalQuantity
0    Chair            562
1  Printer            542
2   Laptop            535
3     Desk            508
4   Tablet            497
5  Monitor            480
6    Phone            411

   Product  TotalQuantity
0    Chair            562
1  Printer            542
2   Laptop            535
3     Desk            508
4   Tablet            497
5  Monitor            480
6    Phone            411

In [33]:
run_query(
"26. Orders By Payment Method",

"""
SELECT
PaymentMethod,
COUNT(*) AS Orders

FROM orders

GROUP BY PaymentMethod

ORDER BY Orders DESC;

"""
)

================================================================================
26. Orders By Payment Method
================================================================================

SELECT
PaymentMethod,
COUNT(*) AS Orders

FROM orders

GROUP BY PaymentMethod

ORDER BY Orders DESC;


--------------------------------------------------------------------------------
  PaymentMethod  Orders
0        Online     258
1          Cash     246
2   Credit Card     234
3    Debit Card     232
4     Gift Card     230

  PaymentMethod  Orders
0        Online     258
1          Cash     246
2   Credit Card     234
3    Debit Card     232
4     Gift Card     230

In [34]:
run_query(
"27. Revenue By Payment Method",

"""
SELECT
PaymentMethod,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY PaymentMethod

ORDER BY Revenue DESC;

"""
)

================================================================================
27. Revenue By Payment Method
================================================================================

SELECT
PaymentMethod,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY PaymentMethod

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

In [35]:
run_query(
"28. Average Order Value By Payment Method",

"""
SELECT
PaymentMethod,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY PaymentMethod

ORDER BY AvgOrderValue DESC;

"""
)

================================================================================
28. Average Order Value By Payment Method
================================================================================

SELECT
PaymentMethod,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY PaymentMethod

ORDER BY AvgOrderValue DESC;


--------------------------------------------------------------------------------
  PaymentMethod  AvgOrderValue
0   Credit Card        1127.55
1     Gift Card        1070.97
2          Cash        1056.04
3        Online        1017.22
4    Debit Card        1001.56

  PaymentMethod  AvgOrderValue
0   Credit Card        1127.55
1     Gift Card        1070.97
2          Cash        1056.04
3        Online        1017.22
4    Debit Card        1001.56

In [36]:
run_query(
"29. Orders By Status",

"""
SELECT
OrderStatus,
COUNT(*) AS Orders

FROM orders

GROUP BY OrderStatus

ORDER BY Orders DESC;

"""
)

================================================================================
29. Orders By Status
================================================================================

SELECT
OrderStatus,
COUNT(*) AS Orders

FROM orders

GROUP BY OrderStatus

ORDER BY Orders DESC;


--------------------------------------------------------------------------------
  OrderStatus  Orders
0   Cancelled     250
1    Returned     247
2     Pending     237
3     Shipped     235
4   Delivered     231

  OrderStatus  Orders
0   Cancelled     250
1    Returned     247
2     Pending     237
3     Shipped     235
4   Delivered     231

In [37]:
run_query(
"30. Revenue By Order Status",

"""
SELECT
OrderStatus,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY OrderStatus

ORDER BY Revenue DESC;

"""
)

================================================================================
30. Revenue By Order Status
================================================================================

SELECT
OrderStatus,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY OrderStatus

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  OrderStatus    Revenue
0   Cancelled  276396.21
1     Pending  256328.15
2     Shipped  246159.58
3    Returned  243277.70
4   Delivered  242600.32

  OrderStatus    Revenue
0   Cancelled  276396.21
1     Pending  256328.15
2     Shipped  246159.58
3    Returned  243277.70
4   Delivered  242600.32

In [38]:
run_query(
"31. Orders By Referral Source",

"""
SELECT
ReferralSource,
COUNT(*) AS Orders

FROM orders

GROUP BY ReferralSource

ORDER BY Orders DESC;

"""
)

================================================================================
31. Orders By Referral Source
================================================================================

SELECT
ReferralSource,
COUNT(*) AS Orders

FROM orders

GROUP BY ReferralSource

ORDER BY Orders DESC;


--------------------------------------------------------------------------------
  ReferralSource  Orders
0      Instagram     259
1          Email     250
2         Google     241
3       Facebook     228
4       Referral     222

  ReferralSource  Orders
0      Instagram     259
1          Email     250
2         Google     241
3       Facebook     228
4       Referral     222

In [39]:
run_query(
"32. Revenue By Referral Source",

"""
SELECT
ReferralSource,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY ReferralSource

ORDER BY Revenue DESC;

"""
)

================================================================================
32. Revenue By Referral Source
================================================================================

SELECT
ReferralSource,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY ReferralSource

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  ReferralSource    Revenue
0      Instagram  275285.45
1          Email  261808.55
2         Google  250441.48
3       Facebook  250410.90
4       Referral  226815.58

  ReferralSource    Revenue
0      Instagram  275285.45
1          Email  261808.55
2         Google  250441.48
3       Facebook  250410.90
4       Referral  226815.58

In [40]:
run_query(
"33. Average Order Value By Referral Source",

"""
SELECT
ReferralSource,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY ReferralSource

ORDER BY AvgOrderValue DESC;

"""
)

================================================================================
33. Average Order Value By Referral Source
================================================================================

SELECT
ReferralSource,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY ReferralSource

ORDER BY AvgOrderValue DESC;


--------------------------------------------------------------------------------
  ReferralSource  AvgOrderValue
0       Facebook        1098.29
1      Instagram        1062.88
2          Email        1047.23
3         Google        1039.18
4       Referral        1021.69

  ReferralSource  AvgOrderValue
0       Facebook        1098.29
1      Instagram        1062.88
2          Email        1047.23
3         Google        1039.18
4       Referral        1021.69

In [41]:
run_query(
"34. Products With Revenue Greater Than ₹150000",

"""
SELECT
Product,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

HAVING Revenue > 150000

ORDER BY Revenue DESC;

"""
)

================================================================================
34. Products With Revenue Greater Than ₹150000
================================================================================

SELECT
Product,
ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

HAVING Revenue > 150000

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

In [42]:
run_query(
"35. Payment Methods With More Than 200 Orders",

"""
SELECT
PaymentMethod,
COUNT(*) AS Orders

FROM orders

GROUP BY PaymentMethod

HAVING Orders > 200;

"""
)

================================================================================
35. Payment Methods With More Than 200 Orders
================================================================================

SELECT
PaymentMethod,
COUNT(*) AS Orders

FROM orders

GROUP BY PaymentMethod

HAVING Orders > 200;


--------------------------------------------------------------------------------
  PaymentMethod  Orders
0          Cash     246
1   Credit Card     234
2    Debit Card     232
3     Gift Card     230
4        Online     258

  PaymentMethod  Orders
0          Cash     246
1   Credit Card     234
2    Debit Card     232
3     Gift Card     230
4        Online     258

In [43]:
run_query(
"36. Referral Sources With Average Order Value Above ₹1000",

"""
SELECT
ReferralSource,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY ReferralSource

HAVING AvgOrderValue > 1000;

"""
)

================================================================================
36. Referral Sources With Average Order Value Above ₹1000
================================================================================

SELECT
ReferralSource,
ROUND(AVG(TotalPrice),2) AS AvgOrderValue

FROM orders

GROUP BY ReferralSource

HAVING AvgOrderValue > 1000;


--------------------------------------------------------------------------------
  ReferralSource  AvgOrderValue
0          Email        1047.23
1       Facebook        1098.29
2         Google        1039.18
3      Instagram        1062.88
4       Referral        1021.69

  ReferralSource  AvgOrderValue
0          Email        1047.23
1       Facebook        1098.29
2         Google        1039.18
3      Instagram        1062.88
4       Referral        1021.69

In [44]:


run_query(
"37. Categorize Orders Based on Total Price",

"""
SELECT
OrderID,
Product,
TotalPrice,

CASE

WHEN TotalPrice >= 2500 THEN 'Premium Order'

WHEN TotalPrice >= 1500 THEN 'High Value'

WHEN TotalPrice >= 700 THEN 'Medium Value'

ELSE 'Low Value'

END AS OrderCategory

FROM orders

ORDER BY TotalPrice DESC;

"""
)

================================================================================
37. Categorize Orders Based on Total Price
================================================================================

SELECT
OrderID,
Product,
TotalPrice,

CASE

WHEN TotalPrice >= 2500 THEN 'Premium Order'

WHEN TotalPrice >= 1500 THEN 'High Value'

WHEN TotalPrice >= 700 THEN 'Medium Value'

ELSE 'Low Value'

END AS OrderCategory

FROM orders

ORDER BY TotalPrice DESC;


--------------------------------------------------------------------------------
        OrderID  Product  TotalPrice  OrderCategory
0     ORD200789   Tablet     3456.40  Premium Order
1     ORD201122  Monitor     3390.95  Premium Order
2     ORD200632   Laptop     3390.80  Premium Order
3     ORD200469    Chair     3384.90  Premium Order
4     ORD200328   Tablet     3370.20  Premium Order
...         ...      ...         ...            ...
1195  ORD200336   Laptop       18.20      Low Value
1196  ORD200542   Tablet       17.98      Low Value
1197  ORD200240   Tablet       17.24      Low Value
1198  ORD200863    Phone       14.06      Low Value
1199  ORD201161    Phone       11.39      Low Value

[1200 rows x 4 columns]

        OrderID  Product  TotalPrice  OrderCategory
0     ORD200789   Tablet     3456.40  Premium Order
1     ORD201122  Monitor     3390.95  Premium Order
2     ORD200632   Laptop     3390.80  Premium Order
3     ORD200469    Chair     3384.90  Premium Order
4     ORD200328   Tablet     3370.20  Premium Order
...         ...      ...         ...            ...
1195  ORD200336   Laptop       18.20      Low Value
1196  ORD200542   Tablet       17.98      Low Value
1197  ORD200240   Tablet       17.24      Low Value
1198  ORD200863    Phone       14.06      Low Value
1199  ORD201161    Phone       11.39      Low Value

[1200 rows x 4 columns]

In [45]:
run_query(
"38. Count Orders By Category",

"""

SELECT

CASE

WHEN TotalPrice >=2500 THEN 'Premium Order'

WHEN TotalPrice >=1500 THEN 'High Value'

WHEN TotalPrice >=700 THEN 'Medium Value'

ELSE 'Low Value'

END AS Category,

COUNT(*) AS TotalOrders

FROM orders

GROUP BY Category;

"""
)

================================================================================
38. Count Orders By Category
================================================================================


SELECT

CASE

WHEN TotalPrice >=2500 THEN 'Premium Order'

WHEN TotalPrice >=1500 THEN 'High Value'

WHEN TotalPrice >=700 THEN 'Medium Value'

ELSE 'Low Value'

END AS Category,

COUNT(*) AS TotalOrders

FROM orders

GROUP BY Category;


--------------------------------------------------------------------------------
        Category  TotalOrders
0     High Value          228
1      Low Value          548
2   Medium Value          330
3  Premium Order           94

        Category  TotalOrders
0     High Value          228
1      Low Value          548
2   Medium Value          330
3  Premium Order           94

In [46]:
run_query(
"39. Revenue Contribution of Each Product",

"""

SELECT

Product,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS RevenuePercentage

FROM orders

GROUP BY Product

ORDER BY Revenue DESC;

"""
)

================================================================================
39. Revenue Contribution of Each Product
================================================================================


SELECT

Product,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS RevenuePercentage

FROM orders

GROUP BY Product

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
   Product    Revenue  RevenuePercentage
0    Chair  195620.11              15.47
1  Printer  195612.61              15.47
2   Laptop  192126.56              15.19
3   Tablet  186568.95              14.75
4  Monitor  175651.41              13.89
5     Desk  167459.93              13.24
6    Phone  151722.39              12.00

   Product    Revenue  RevenuePercentage
0    Chair  195620.11              15.47
1  Printer  195612.61              15.47
2   Laptop  192126.56              15.19
3   Tablet  186568.95              14.75
4  Monitor  175651.41              13.89
5     Desk  167459.93              13.24
6    Phone  151722.39              12.00

In [47]:
run_query(
"40. Revenue Contribution By Payment Method",

"""

SELECT

PaymentMethod,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS Contribution

FROM orders

GROUP BY PaymentMethod

ORDER BY Revenue DESC;

"""
)

================================================================================
40. Revenue Contribution By Payment Method
================================================================================


SELECT

PaymentMethod,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS Contribution

FROM orders

GROUP BY PaymentMethod

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  PaymentMethod    Revenue  Contribution
0   Credit Card  263847.63         20.86
1        Online  262442.94         20.75
2          Cash  259786.29         20.54
3     Gift Card  246323.92         19.48
4    Debit Card  232361.18         18.37

  PaymentMethod    Revenue  Contribution
0   Credit Card  263847.63         20.86
1        Online  262442.94         20.75
2          Cash  259786.29         20.54
3     Gift Card  246323.92         19.48
4    Debit Card  232361.18         18.37

In [48]:
run_query(
"41. Referral Source Contribution",

"""

SELECT

ReferralSource,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS Contribution

FROM orders

GROUP BY ReferralSource

ORDER BY Revenue DESC;

"""
)

================================================================================
41. Referral Source Contribution
================================================================================


SELECT

ReferralSource,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(

SUM(TotalPrice)*100.0/

(SELECT SUM(TotalPrice) FROM orders),

2

) AS Contribution

FROM orders

GROUP BY ReferralSource

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  ReferralSource    Revenue  Contribution
0      Instagram  275285.45         21.77
1          Email  261808.55         20.70
2         Google  250441.48         19.80
3       Facebook  250410.90         19.80
4       Referral  226815.58         17.93

  ReferralSource    Revenue  Contribution
0      Instagram  275285.45         21.77
1          Email  261808.55         20.70
2         Google  250441.48         19.80
3       Facebook  250410.90         19.80
4       Referral  226815.58         17.93

In [49]:
run_query(
"42. Top Customers By Spending",

"""

SELECT

CustomerID,

COUNT(*) AS Orders,

ROUND(SUM(TotalPrice),2) AS TotalSpent

FROM orders

GROUP BY CustomerID

ORDER BY TotalSpent DESC

LIMIT 10;

"""
)

================================================================================
42. Top Customers By Spending
================================================================================


SELECT

CustomerID,

COUNT(*) AS Orders,

ROUND(SUM(TotalPrice),2) AS TotalSpent

FROM orders

GROUP BY CustomerID

ORDER BY TotalSpent DESC

LIMIT 10;


--------------------------------------------------------------------------------
  CustomerID  Orders  TotalSpent
0     C38840       2     5723.23
1     C57276       1     3456.40
2     C67260       1     3390.80
3     C13877       1     3384.90
4     C18404       1     3370.20
5     C16775       1     3353.75
6     C65986       1     3352.40
7     C47778       1     3334.00
8     C59183       1     3322.55
9     C25276       1     3313.90

  CustomerID  Orders  TotalSpent
0     C38840       2     5723.23
1     C57276       1     3456.40
2     C67260       1     3390.80
3     C13877       1     3384.90
4     C18404       1     3370.20
5     C16775       1     3353.75
6     C65986       1     3352.40
7     C47778       1     3334.00
8     C59183       1     3322.55
9     C25276       1     3313.90

In [50]:
run_query(
"43. Customers With More Than One Order",

"""

SELECT

CustomerID,

COUNT(*) AS TotalOrders

FROM orders

GROUP BY CustomerID

HAVING COUNT(*)>1

ORDER BY TotalOrders DESC;

"""
)

================================================================================
43. Customers With More Than One Order
================================================================================


SELECT

CustomerID,

COUNT(*) AS TotalOrders

FROM orders

GROUP BY CustomerID

HAVING COUNT(*)>1

ORDER BY TotalOrders DESC;


--------------------------------------------------------------------------------
   CustomerID  TotalOrders
0      C98474            2
1      C97593            2
2      C94569            2
3      C91155            2
4      C70659            2
5      C56969            2
6      C46651            2
7      C38840            2
8      C35852            2
9      C21191            2
10     C14847            2

   CustomerID  TotalOrders
0      C98474            2
1      C97593            2
2      C94569            2
3      C91155            2
4      C70659            2
5      C56969            2
6      C46651            2
7      C38840            2
8      C35852            2
9      C21191            2
10     C14847            2

In [51]:
run_query(
"44. Products With Highest Quantity Sold",

"""

SELECT

Product,

SUM(Quantity) AS QuantitySold

FROM orders

GROUP BY Product

ORDER BY QuantitySold DESC;

"""
)

================================================================================
44. Products With Highest Quantity Sold
================================================================================


SELECT

Product,

SUM(Quantity) AS QuantitySold

FROM orders

GROUP BY Product

ORDER BY QuantitySold DESC;


--------------------------------------------------------------------------------
   Product  QuantitySold
0    Chair           562
1  Printer           542
2   Laptop           535
3     Desk           508
4   Tablet           497
5  Monitor           480
6    Phone           411

   Product  QuantitySold
0    Chair           562
1  Printer           542
2   Laptop           535
3     Desk           508
4   Tablet           497
5  Monitor           480
6    Phone           411

In [52]:
run_query(
"45. Average Quantity Per Product",

"""

SELECT

Product,

ROUND(AVG(Quantity),2) AS AvgQuantity

FROM orders

GROUP BY Product

ORDER BY AvgQuantity DESC;

"""
)

================================================================================
45. Average Quantity Per Product
================================================================================


SELECT

Product,

ROUND(AVG(Quantity),2) AS AvgQuantity

FROM orders

GROUP BY Product

ORDER BY AvgQuantity DESC;


--------------------------------------------------------------------------------
   Product  AvgQuantity
0    Chair         3.16
1   Laptop         3.09
2  Printer         2.99
3     Desk         2.99
4  Monitor         2.94
5   Tablet         2.78
6    Phone         2.63

   Product  AvgQuantity
0    Chair         3.16
1   Laptop         3.09
2  Printer         2.99
3     Desk         2.99
4  Monitor         2.94
5   Tablet         2.78
6    Phone         2.63

In [53]:
run_query(
"46. Average Cart Size",

"""

SELECT

ROUND(AVG(ItemsInCart),2) AS AverageCartSize

FROM orders;

"""
)

================================================================================
46. Average Cart Size
================================================================================


SELECT

ROUND(AVG(ItemsInCart),2) AS AverageCartSize

FROM orders;


--------------------------------------------------------------------------------
   AverageCartSize
0             5.49

   AverageCartSize
0             5.49

In [54]:
run_query(
"47. Orders Having More Than Three Items",

"""

SELECT

OrderID,

ItemsInCart,

TotalPrice

FROM orders

WHERE ItemsInCart>3

ORDER BY ItemsInCart DESC;

"""
)

================================================================================
47. Orders Having More Than Three Items
================================================================================


SELECT

OrderID,

ItemsInCart,

TotalPrice

FROM orders

WHERE ItemsInCart>3

ORDER BY ItemsInCart DESC;


--------------------------------------------------------------------------------
       OrderID  ItemsInCart  TotalPrice
0    ORD200032           10     2683.60
1    ORD200177           10     2158.45
2    ORD200180           10     1580.35
3    ORD200181           10     2021.95
4    ORD200256           10      379.05
..         ...          ...         ...
944  ORD201178            4       70.24
945  ORD201184            4      204.08
946  ORD201192            4     1298.55
947  ORD201194            4      568.32
948  ORD201198            4     1050.08

[949 rows x 3 columns]

       OrderID  ItemsInCart  TotalPrice
0    ORD200032           10     2683.60
1    ORD200177           10     2158.45
2    ORD200180           10     1580.35
3    ORD200181           10     2021.95
4    ORD200256           10      379.05
..         ...          ...         ...
944  ORD201178            4       70.24
945  ORD201184            4      204.08
946  ORD201192            4     1298.55
947  ORD201194            4      568.32
948  ORD201198            4     1050.08

[949 rows x 3 columns]

In [55]:
run_query(
"48. Orders By Coupon Code",

"""

SELECT

CouponCode,

COUNT(*) AS Orders

FROM orders

GROUP BY CouponCode

ORDER BY Orders DESC;

"""
)

================================================================================
48. Orders By Coupon Code
================================================================================


SELECT

CouponCode,

COUNT(*) AS Orders

FROM orders

GROUP BY CouponCode

ORDER BY Orders DESC;


--------------------------------------------------------------------------------
  CouponCode  Orders
0   FREESHIP     313
1       None     309
2   WINTER15     292
3     SAVE10     286

  CouponCode  Orders
0   FREESHIP     313
1       None     309
2   WINTER15     292
3     SAVE10     286

In [56]:
run_query(
"49. Revenue By Coupon Code",

"""

SELECT

CouponCode,

ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY CouponCode

ORDER BY Revenue DESC;

"""
)

================================================================================
49. Revenue By Coupon Code
================================================================================


SELECT

CouponCode,

ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY CouponCode

ORDER BY Revenue DESC;


--------------------------------------------------------------------------------
  CouponCode    Revenue
0   FREESHIP  335036.99
1       None  322401.41
2     SAVE10  304840.02
3   WINTER15  302483.54

  CouponCode    Revenue
0   FREESHIP  335036.99
1       None  322401.41
2     SAVE10  304840.02
3   WINTER15  302483.54

In [57]:
run_query(
"50. Top Five Products By Revenue",

"""

SELECT

Product,

ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

ORDER BY Revenue DESC

LIMIT 5;

"""
)

================================================================================
50. Top Five Products By Revenue
================================================================================


SELECT

Product,

ROUND(SUM(TotalPrice),2) AS Revenue

FROM orders

GROUP BY Product

ORDER BY Revenue DESC

LIMIT 5;


--------------------------------------------------------------------------------
   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41

In [58]:
run_query(
"51. Complete Business Dashboard Summary",

"""

SELECT

COUNT(*) AS TotalOrders,

COUNT(DISTINCT CustomerID) AS TotalCustomers,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(AVG(TotalPrice),2) AS AvgOrder,

MAX(TotalPrice) AS HighestOrder,

MIN(TotalPrice) AS LowestOrder

FROM orders;

"""
)

================================================================================
51. Complete Business Dashboard Summary
================================================================================


SELECT

COUNT(*) AS TotalOrders,

COUNT(DISTINCT CustomerID) AS TotalCustomers,

ROUND(SUM(TotalPrice),2) AS Revenue,

ROUND(AVG(TotalPrice),2) AS AvgOrder,

MAX(TotalPrice) AS HighestOrder,

MIN(TotalPrice) AS LowestOrder

FROM orders;


--------------------------------------------------------------------------------
   TotalOrders  TotalCustomers     Revenue  AvgOrder  HighestOrder  \
0         1200            1189  1264761.96   1053.97        3456.4

   LowestOrder
0        11.39

,TotalOrders,TotalCustomers,Revenue,AvgOrder,HighestOrder,LowestOrder
0,1200,1189,1264761.96,1053.97,3456.4,11.39